package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"terraform-provider-superset/internal/client"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &chartResource{}
	_ resource.ResourceWithConfigure   = &chartResource{}
	_ resource.ResourceWithImportState = &chartResource{}
)

// NewChartResource is a helper function to simplify the provider implementation.
func NewChartResource() resource.Resource {
	return &chartResource{}
}

// chartResource is the resource implementation.
type chartResource struct {
	client *client.Client
}

// chartResourceModel maps the resource schema data.
type chartResourceModel struct {
	ID             types.Int64  `tfsdk:"id"`
	SliceName      types.String `tfsdk:"slice_name"`
	DatasourceID   types.Int64  `tfsdk:"datasource_id"`
	DatasourceType types.String `tfsdk:"datasource_type"`
	VizType        types.String `tfsdk:"viz_type"`
	Description    types.String `tfsdk:"description"`
	Params         types.String `tfsdk:"params"`
	CacheTimeout   types.Int64  `tfsdk:"cache_timeout"`
	CertifiedBy    types.String `tfsdk:"certified_by"`
	CertDetails    types.String `tfsdk:"certification_details"`
	Dashboards     types.List   `tfsdk:"dashboards"`
}

// Metadata returns the resource type name.
func (r *chartResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_chart"
}

// Schema defines the schema for the resource.
func (r *chartResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a chart (slice) in Superset.",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "Numeric identifier of the chart.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"slice_name": schema.StringAttribute{
				Description: "The name of the chart.",
				Required:    true,
			},
			"datasource_id": schema.Int64Attribute{
				Description: "The ID of the dataset/datasource this chart uses.",
				Required:    true,
			},
			"datasource_type": schema.StringAttribute{
				Description: "The type of dataset/datasource. Usually 'table' for datasets.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("table"),
			},
			"viz_type": schema.StringAttribute{
				Description: "The type of chart visualization (e.g., 'table', 'pie', 'bar', 'line', 'big_number', etc.).",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("table"),
			},
			"description": schema.StringAttribute{
				Description: "A description of the chart's purpose.",
				Optional:    true,
			},
			"params": schema.StringAttribute{
				Description: "JSON string containing chart parameters and configuration. " +
					"These are generated by Superset's chart builder and control the chart's appearance and behavior.",
				Optional: true,
			},
			"cache_timeout": schema.Int64Attribute{
				Description: "Duration (in seconds) of the caching timeout for this chart.",
				Optional:    true,
			},
			"certified_by": schema.StringAttribute{
				Description: "Person or group that has certified this chart.",
				Optional:    true,
			},
			"certification_details": schema.StringAttribute{
				Description: "Details of the certification.",
				Optional:    true,
			},
			"dashboards": schema.ListAttribute{
				Description: "List of dashboard IDs that this chart belongs to. " +
					"Adding a dashboard ID here will link the chart to that dashboard.",
				Optional:    true,
				ElementType: types.Int64Type,
			},
		},
	}
}

// Create creates the resource and sets the initial Terraform state.
func (r *chartResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// Retrieve values from plan
	var plan chartResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Creating chart", map[string]interface{}{
		"slice_name":    plan.SliceName.ValueString(),
		"datasource_id": plan.DatasourceID.ValueInt64(),
	})

	// Build create request
	chartReq := client.ChartCreateRequest{
		SliceName:      plan.SliceName.ValueString(),
		DatasourceID:   plan.DatasourceID.ValueInt64(),
		DatasourceType: plan.DatasourceType.ValueString(),
		VizType:        plan.VizType.ValueString(),
		Description:    plan.Description.ValueString(),
		Params:         plan.Params.ValueString(),
		CertifiedBy:    plan.CertifiedBy.ValueString(),
		CertDetails:    plan.CertDetails.ValueString(),
	}

	if !plan.CacheTimeout.IsNull() && !plan.CacheTimeout.IsUnknown() {
		ct := plan.CacheTimeout.ValueInt64()
		chartReq.CacheTimeout = &ct
	}

	// Add dashboards if specified
	if !plan.Dashboards.IsNull() && !plan.Dashboards.IsUnknown() {
		var dashboardIDs []int64
		diags = plan.Dashboards.ElementsAs(ctx, &dashboardIDs, false)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		chartReq.Dashboards = dashboardIDs
	}

	// Create chart
	chartID, err := r.client.CreateChart(chartReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating chart",
			"Could not create chart: "+err.Error(),
		)
		return
	}

	// Update the state with the ID
	plan.ID = types.Int64Value(chartID)

	// Read back the chart to get computed values
	chart, err := r.client.GetChart(chartID)
	if err != nil {
		tflog.Warn(ctx, "Could not read back chart after creation", map[string]interface{}{
			"id":    chartID,
			"error": err.Error(),
		})
	} else {
		// Update computed values from API response
		plan.DatasourceType = types.StringValue(chart.DatasourceType)
		plan.VizType = types.StringValue(chart.VizType)
	}

	tflog.Debug(ctx, "Created chart", map[string]interface{}{
		"id": chartID,
	})

	// Set state to fully populated data
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Read refreshes the Terraform state with the latest data.
func (r *chartResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Get current state
	var state chartResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get chart from API
	chart, err := r.client.GetChart(state.ID.ValueInt64())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading chart",
			"Could not read chart ID "+fmt.Sprintf("%d", state.ID.ValueInt64())+": "+err.Error(),
		)
		return
	}

	// Update state from API response
	state.SliceName = types.StringValue(chart.SliceName)
	state.DatasourceID = types.Int64Value(chart.DatasourceID)
	state.DatasourceType = types.StringValue(chart.DatasourceType)
	state.VizType = types.StringValue(chart.VizType)

	if chart.Description != "" {
		state.Description = types.StringValue(chart.Description)
	} else {
		state.Description = types.StringNull()
	}

	if chart.Params != "" {
		state.Params = types.StringValue(chart.Params)
	} else {
		state.Params = types.StringNull()
	}

	if chart.CacheTimeout != nil {
		state.CacheTimeout = types.Int64Value(*chart.CacheTimeout)
	} else {
		state.CacheTimeout = types.Int64Null()
	}

	if chart.CertifiedBy != "" {
		state.CertifiedBy = types.StringValue(chart.CertifiedBy)
	} else {
		state.CertifiedBy = types.StringNull()
	}

	if chart.CertDetails != "" {
		state.CertDetails = types.StringValue(chart.CertDetails)
	} else {
		state.CertDetails = types.StringNull()
	}

	// Set refreshed state
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *chartResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Retrieve values from plan
	var plan chartResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Build update request
	updateReq := client.ChartUpdateRequest{
		SliceName:      plan.SliceName.ValueString(),
		DatasourceID:   plan.DatasourceID.ValueInt64(),
		DatasourceType: plan.DatasourceType.ValueString(),
		VizType:        plan.VizType.ValueString(),
		Description:    plan.Description.ValueString(),
		Params:         plan.Params.ValueString(),
		CertifiedBy:    plan.CertifiedBy.ValueString(),
		CertDetails:    plan.CertDetails.ValueString(),
	}

	if !plan.CacheTimeout.IsNull() && !plan.CacheTimeout.IsUnknown() {
		ct := plan.CacheTimeout.ValueInt64()
		updateReq.CacheTimeout = &ct
	}

	// Add dashboards if specified
	if !plan.Dashboards.IsNull() && !plan.Dashboards.IsUnknown() {
		var dashboardIDs []int64
		diags = plan.Dashboards.ElementsAs(ctx, &dashboardIDs, false)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		updateReq.Dashboards = dashboardIDs
	}

	// Update chart
	err := r.client.UpdateChart(plan.ID.ValueInt64(), updateReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating chart",
			"Could not update chart ID "+fmt.Sprintf("%d", plan.ID.ValueInt64())+": "+err.Error(),
		)
		return
	}

	tflog.Debug(ctx, "Updated chart", map[string]interface{}{
		"id": plan.ID.ValueInt64(),
	})

	// Set updated state
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *chartResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Retrieve values from state
	var state chartResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Delete existing chart
	err := r.client.DeleteChart(state.ID.ValueInt64())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error deleting chart",
			"Could not delete chart, unexpected error: "+err.Error(),
		)
		return
	}

	tflog.Debug(ctx, "Deleted chart", map[string]interface{}{
		"id": state.ID.ValueInt64(),
	})
}

// Configure adds the provider configured client to the resource.
func (r *chartResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

// ImportState imports the resource state.
func (r *chartResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Retrieve import ID and save to id attribute
	id, err := strconv.ParseInt(req.ID, 10, 64)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error importing chart",
			"Could not parse chart ID: "+err.Error(),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}

