package provider

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"terraform-provider-superset/internal/client"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &dashboardResource{}
	_ resource.ResourceWithConfigure   = &dashboardResource{}
	_ resource.ResourceWithImportState = &dashboardResource{}
)

// NewDashboardResource is a helper function to simplify the provider implementation.
func NewDashboardResource() resource.Resource {
	return &dashboardResource{}
}

// dashboardResource is the resource implementation.
type dashboardResource struct {
	client *client.Client
}

// dashboardResourceModel maps the resource schema data.
type dashboardResourceModel struct {
	ID             types.Int64  `tfsdk:"id"`
	DashboardTitle types.String `tfsdk:"dashboard_title"`
	Slug           types.String `tfsdk:"slug"`
	Published      types.Bool   `tfsdk:"published"`
	JsonMetadata   types.String `tfsdk:"json_metadata"`
	PositionJSON   types.String `tfsdk:"position_json"`
	CSS            types.String `tfsdk:"css"`
	CertifiedBy    types.String `tfsdk:"certified_by"`
	CertDetails    types.String `tfsdk:"certification_details"`
}

// Metadata returns the resource type name.
func (r *dashboardResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dashboard"
}

// Schema defines the schema for the resource.
func (r *dashboardResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a dashboard in Superset.",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Description: "Numeric identifier of the dashboard.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"dashboard_title": schema.StringAttribute{
				Description: "The title of the dashboard.",
				Required:    true,
			},
			"slug": schema.StringAttribute{
				Description: "Unique identifying part for the web address of the dashboard. " +
					"If not provided, Superset will generate one from the title.",
				Optional: true,
				Computed: true,
			},
			"published": schema.BoolAttribute{
				Description: "Determines whether or not this dashboard is visible in the list of dashboards.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},
			"json_metadata": schema.StringAttribute{
				Description: "JSON object containing dashboard metadata such as filter configurations, " +
					"default filters, and chart refresh settings. Generated by Superset's dashboard builder.",
				Optional: true,
			},
			"position_json": schema.StringAttribute{
				Description: "JSON object describing the positioning of widgets/charts in the dashboard. " +
					"This defines the dashboard layout and is typically generated by the dashboard editor.",
				Optional: true,
			},
			"css": schema.StringAttribute{
				Description: "Custom CSS to override the dashboard's styling.",
				Optional:    true,
			},
			"certified_by": schema.StringAttribute{
				Description: "Person or group that has certified this dashboard.",
				Optional:    true,
			},
			"certification_details": schema.StringAttribute{
				Description: "Details of the certification.",
				Optional:    true,
			},
		},
	}
}

// Create creates the resource and sets the initial Terraform state.
func (r *dashboardResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// Retrieve values from plan
	var plan dashboardResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, "Creating dashboard", map[string]interface{}{
		"dashboard_title": plan.DashboardTitle.ValueString(),
	})

	// Build create request
	dashboardReq := client.DashboardCreateRequest{
		DashboardTitle: plan.DashboardTitle.ValueString(),
		Slug:           plan.Slug.ValueString(),
		Published:      plan.Published.ValueBool(),
		JsonMetadata:   plan.JsonMetadata.ValueString(),
		PositionJSON:   plan.PositionJSON.ValueString(),
		CSS:            plan.CSS.ValueString(),
		CertifiedBy:    plan.CertifiedBy.ValueString(),
		CertDetails:    plan.CertDetails.ValueString(),
	}

	// Create dashboard
	dashboardID, err := r.client.CreateDashboard(dashboardReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error creating dashboard",
			"Could not create dashboard: "+err.Error(),
		)
		return
	}

	// Update the state with the ID
	plan.ID = types.Int64Value(dashboardID)

	// Read back the dashboard to get computed values (like generated slug)
	dashboard, err := r.client.GetDashboard(dashboardID)
	if err != nil {
		tflog.Warn(ctx, "Could not read back dashboard after creation", map[string]interface{}{
			"id":    dashboardID,
			"error": err.Error(),
		})
		// Set slug to empty string if we can't read it back
		if plan.Slug.IsUnknown() {
			plan.Slug = types.StringValue("")
		}
	} else {
		// Always set slug from API response (even if empty)
		plan.Slug = types.StringValue(dashboard.Slug)
	}

	tflog.Debug(ctx, "Created dashboard", map[string]interface{}{
		"id": dashboardID,
	})

	// Set state to fully populated data
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Read refreshes the Terraform state with the latest data.
func (r *dashboardResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Get current state
	var state dashboardResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get dashboard from API
	dashboard, err := r.client.GetDashboard(state.ID.ValueInt64())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading dashboard",
			"Could not read dashboard ID "+fmt.Sprintf("%d", state.ID.ValueInt64())+": "+err.Error(),
		)
		return
	}

	// Update state from API response
	state.DashboardTitle = types.StringValue(dashboard.DashboardTitle)
	state.Published = types.BoolValue(dashboard.Published)

	if dashboard.Slug != "" {
		state.Slug = types.StringValue(dashboard.Slug)
	} else {
		state.Slug = types.StringNull()
	}

	// Avoid perpetual diffs:
	// The client intentionally merges `position_json` into `json_metadata` to trigger
	// Superset's chart linking behavior. Superset will then return a mutated
	// `json_metadata` (with `positions`) which will not byte-match the configured
	// json_metadata. If the user configured json_metadata, keep it in state.
	if state.JsonMetadata.IsNull() || state.JsonMetadata.IsUnknown() {
		if dashboard.JsonMetadata != "" {
			state.JsonMetadata = types.StringValue(dashboard.JsonMetadata)
		} else {
			state.JsonMetadata = types.StringNull()
		}
	}

	// If the user configured position_json, keep it in state (Superset may normalize).
	if state.PositionJSON.IsNull() || state.PositionJSON.IsUnknown() {
		if dashboard.PositionJSON != "" {
			state.PositionJSON = types.StringValue(dashboard.PositionJSON)
		} else {
			state.PositionJSON = types.StringNull()
		}
	}

	if dashboard.CSS != "" {
		state.CSS = types.StringValue(dashboard.CSS)
	} else {
		state.CSS = types.StringNull()
	}

	if dashboard.CertifiedBy != "" {
		state.CertifiedBy = types.StringValue(dashboard.CertifiedBy)
	} else {
		state.CertifiedBy = types.StringNull()
	}

	if dashboard.CertDetails != "" {
		state.CertDetails = types.StringValue(dashboard.CertDetails)
	} else {
		state.CertDetails = types.StringNull()
	}

	// Set refreshed state
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *dashboardResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Retrieve values from plan
	var plan dashboardResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Build update request
	published := plan.Published.ValueBool()
	updateReq := client.DashboardUpdateRequest{
		DashboardTitle: plan.DashboardTitle.ValueString(),
		Slug:           plan.Slug.ValueString(),
		Published:      &published,
		JsonMetadata:   plan.JsonMetadata.ValueString(),
		PositionJSON:   plan.PositionJSON.ValueString(),
		CSS:            plan.CSS.ValueString(),
		CertifiedBy:    plan.CertifiedBy.ValueString(),
		CertDetails:    plan.CertDetails.ValueString(),
	}

	// Update dashboard
	err := r.client.UpdateDashboard(plan.ID.ValueInt64(), updateReq)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error updating dashboard",
			"Could not update dashboard ID "+fmt.Sprintf("%d", plan.ID.ValueInt64())+": "+err.Error(),
		)
		return
	}

	tflog.Debug(ctx, "Updated dashboard", map[string]interface{}{
		"id": plan.ID.ValueInt64(),
	})

	// Read back the dashboard to get actual values (especially computed fields like slug)
	dashboard, err := r.client.GetDashboard(plan.ID.ValueInt64())
	if err != nil {
		tflog.Warn(ctx, "Could not read back dashboard after update", map[string]interface{}{
			"id":    plan.ID.ValueInt64(),
			"error": err.Error(),
		})
		// Set slug to empty if we can't read it
		if plan.Slug.IsUnknown() {
			plan.Slug = types.StringValue("")
		}
	} else {
		// Set slug from API response
		plan.Slug = types.StringValue(dashboard.Slug)
	}

	// Set updated state
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *dashboardResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Retrieve values from state
	var state dashboardResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Delete existing dashboard
	err := r.client.DeleteDashboard(state.ID.ValueInt64())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error deleting dashboard",
			"Could not delete dashboard, unexpected error: "+err.Error(),
		)
		return
	}

	tflog.Debug(ctx, "Deleted dashboard", map[string]interface{}{
		"id": state.ID.ValueInt64(),
	})
}

// Configure adds the provider configured client to the resource.
func (r *dashboardResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*client.Client)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

// ImportState imports the resource state.
func (r *dashboardResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Retrieve import ID and save to id attribute
	id, err := strconv.ParseInt(req.ID, 10, 64)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error importing dashboard",
			"Could not parse dashboard ID: "+err.Error(),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}

